appName: sx-api
namespace: mainnet

nodeSelector:
  doks.digitalocean.com/node-pool: mainnet-pool
tolerations:
  - key: workload
    operator: Equal
    value: mainnet
    effect: NoSchedule

image:
  repository: ghcr.io/snapshot-labs/sx-api

db:
  storage: 20Gi

config:
  PORT: '3000'
  ENABLED_NETWORKS: 'eth,oeth,base,mnt,arb1,ape,bnb,sn'
