/**
 * The digest an authorised protocol request is signed over, ported for the browser.
 *
 * This is a byte-exact mirror of the hub's `helpers/gegDigests.ts` `requestDigest`
 * and of geg's `geg.core.authz.request_digest`. It lives here rather than being
 * imported because the hub's copy is a Node module built around `Buffer`, and this
 * is the only piece of it the UI needs: the admin's "retry" is the one protocol
 * write a human signs in a wallet.
 *
 * Each field is **length-framed** — a 4-byte big-endian length, then the bytes —
 * under a domain-separation tag. The framing is what makes the operation name part
 * of the signature rather than a parameter beside it, so a signature taken for
 * `tally_stall` cannot be presented as a `tally_resume`. An earlier encoding joined
 * the fields with `|`, under which `("tally", "_resume…")` and `("tally_resume", …)`
 * hashed equal and shared a signature.
 *
 * The digest is signed as raw bytes under EIP-191 (`signMessage` over the 32-byte
 * array, *not* over its hex string), which is what the hub's `verifyMessage`
 * expects. `gegRequest.test.ts` locks all of this against vectors generated by
 * geg's Python.
 */

import { arrayify } from '@ethersproject/bytes';
import { keccak256 } from '@ethersproject/keccak256';

const REQUEST_DST = new TextEncoder().encode('GEG-REQUEST-v1');

function u32BE(n: number): Uint8Array {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, n, false);
  return b;
}

function concatBytes(parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let at = 0;
  for (const p of parts) {
    out.set(p, at);
    at += p.length;
  }
  return out;
}

/**
 * The freshness term a stall/resume request carries as its payload.
 *
 * Eight bytes, big-endian, unsigned seconds. Byte-exact with the hub's
 * `requestNoncePayload` and geg's `request_nonce_payload`.
 */
export function requestNoncePayload(issuedAt: number): Uint8Array {
  if (!Number.isInteger(issuedAt) || issuedAt < 0) {
    throw new Error(`issuedAt must be a non-negative integer, got ${issuedAt}`);
  }
  const b = new Uint8Array(8);
  new DataView(b.buffer).setBigUint64(0, BigInt(issuedAt), false);
  return b;
}

/**
 * `keccak256(DST ‖ len|op ‖ len|electionId ‖ len|payload)` as raw bytes.
 *
 * `electionId` is the Snapshot proposal id, which the protocol reads as the 32-byte
 * election id. A wrong-sized id is rejected rather than padded: the hub enforces the
 * same, and silently accepting one would produce a digest no verifier reproduces.
 */
export function requestDigest(
  op: string,
  electionId: string,
  payload: Uint8Array = new Uint8Array(0)
): Uint8Array {
  const eid = arrayify(electionId);
  if (eid.length !== 32) {
    throw new Error(
      `electionId must be 32 bytes, got ${eid.length} — the protocol reads it as bytes32`
    );
  }
  const opBytes = new TextEncoder().encode(op);
  const packed = concatBytes([
    REQUEST_DST,
    u32BE(opBytes.length),
    opBytes,
    u32BE(eid.length),
    eid,
    u32BE(payload.length),
    payload
  ]);
  return arrayify(keccak256(packed));
}
