version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 0
    allow:
      - dependency-name: "@snapshot-labs/*"
    ignore:
      - dependency-name: "@snapshot-labs/checkpoint"
    groups:
      snapshot:
        patterns:
        - "@snapshot-labs/*"
