import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import unicorn from 'eslint-plugin-unicorn'

export default [
  {
    ignores: ['**/node_modules/**', '**/dist/**', 'bun.lock', '**/*.d.ts'],
  },
  {
    files: ['**/*.{js,mjs,ts}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    rules: {
      'max-lines': ['error', { max: 500, skipBlankLines: false, skipComments: false }],
      'max-len': ['error', { code: 140, ignoreComments: true, ignoreTemplateLiterals: true, ignoreStrings: true }],
      'max-lines-per-function': ['error', { max: 200, skipBlankLines: false, skipComments: false }],
      'no-unused-vars': ['error', { vars: 'all', args: 'none', caughtErrors: 'none', ignoreRestSiblings: true, varsIgnorePattern: '^_' }],
      'no-console': ['error', { allow: ['log', 'error', 'warn'] }],
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'prefer-const': 'error',
      'object-shorthand': 'error',
      'object-curly-spacing': ['error', 'always'],
      'padding-line-between-statements': ['error',
        { blankLine: 'always', prev: '*', next: 'function' },
        { blankLine: 'always', prev: 'function', next: '*' },
        { blankLine: 'always', prev: '*', next: 'class' },
        { blankLine: 'always', prev: 'class', next: '*' },
        { blankLine: 'always', prev: 'import', next: '*' },
        { blankLine: 'any', prev: 'import', next: 'import' },
        { blankLine: 'any', prev: 'export', next: 'export' },
      ],
      'no-eval': 'error',
      'no-new-func': 'error',
      'no-implied-eval': 'error',
      'no-shadow': ['error', { builtinGlobals: false, hoist: 'functions' }],
      'no-else-return': 'error',
      'max-params': ['error', 4],
      'max-depth': ['error', 3],
      'no-promise-executor-return': 'error',
      'no-restricted-syntax': ['error',
        { selector: 'ForInStatement', message: 'Use for...of or Object.entries() instead of for...in. it iterates the prototype chain.' },
        { selector: 'WithStatement', message: 'with is banned.' },
        { selector: "ExpressionStatement > UnaryExpression[operator='void'] > CallExpression", message: "Use 'await' or explicit .catch() instead of void to suppress promise warnings." },
      ],
    },
  },
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { '@typescript-eslint': tsPlugin },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports', fixStyle: 'inline-type-imports' }],
      'no-duplicate-imports': 'error',
      '@typescript-eslint/naming-convention': [
        'error',
        { selector: 'variable', format: null, filter: { regex: '^(__|[a-z]+(_[a-z]+)+$)', match: true } },
        { selector: 'typeLike', format: ['PascalCase'] },
        { selector: 'variable', format: ['camelCase', 'UPPER_CASE', 'PascalCase'], leadingUnderscore: 'allow' },
        { selector: 'function', format: ['camelCase'] },
        { selector: 'interface', format: ['PascalCase'], custom: { regex: '^(?!I[A-Z])', match: true } },
        { selector: 'typeParameter', format: ['PascalCase'], prefix: ['T'] },
      ],
      'quotes': ['error', 'single', { avoidEscape: true }],
    },
  },
  {
    files: ['src/**/*.ts'],
    plugins: { '@typescript-eslint': tsPlugin },
    rules: {
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: { attributes: false } }],
      '@typescript-eslint/return-await': ['error', 'in-try-catch'],
      '@typescript-eslint/only-throw-error': 'error',
      '@typescript-eslint/explicit-function-return-type': ['error', { allowExpressions: true, allowTypedFunctionExpressions: true }],
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      '@typescript-eslint/strict-boolean-expressions': ['error', { allowNullableObject: true, allowNullableBoolean: true, allowNullableString: true }],
      '@typescript-eslint/prefer-nullish-coalescing': ['error', { ignoreMixedLogicalExpressions: false }],
      '@typescript-eslint/prefer-optional-chain': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
    },
  },
  {
    files: ['tests/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    files: ['**/*.ts'],
    ignores: ['**/*.d.ts'],
    plugins: { unicorn },
    rules: {
      'unicorn/filename-case': ['error', { case: 'kebabCase', multipleFileExtensions: false }],
      'unicorn/catch-error-name': ['error', { name: 'e' }],
      'unicorn/prefer-includes': 'error',
      'unicorn/no-process-exit': 'error',
    },
  },
]
