apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-{{ .Values.color }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
