scalar Id
scalar Text

type Space {
  id: String
  voting_delay: Int
  voting_period: Int
  proposal_threshold: Int
  created: Int
}

type Proposal {
  id: String
  space: String
  author: String
  execution: String
  metadata: String
  title: Text
  body: Text
  start: Int
  end: Int
  snapshot: Int
  created: Int
  tx: String
  vote_count: Int
}

type Vote {
  id: String
  voter: String
  space: String
  proposal: Int
  choice: Int
  vp: Int
  created: Int
}
