/**
 * Cross-language parity for the keyper write digests.
 *
 * A keyper computes and signs these in Python; the hub recomputes them in
 * TypeScript to recover the signer. If the two constructions drift, every
 * legitimate keyper write is rejected as a bad signature — a failure that looks
 * like an authorisation problem and gives no hint that it is really an encoding
 * one. So the digests are pinned against vectors generated by geg's own
 * `write_auth`, in `test/fixtures/geg-digests.json`.
 *
 * Regenerate the fixture after any change to the digest definition:
 *
 *   cd <geg-repo> && .venv/bin/python -c "…"   # see scripts/geg/ for the pattern
 *
 * The committee sizes covered are deliberate rather than arbitrary. `bytes[]` is a
 * dynamic array of dynamic elements, so its ABI encoding is a table of offsets
 * followed by length-prefixed padded data — the layout differs between one element
 * and several, which is exactly where a hand-rolled encoder would go wrong.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  dkgResultDigest,
  GegDigestError,
  recoverDigestSigner,
  requestDigest,
  requestNoncePayload
} from '../../src/helpers/gegDigests';

type DigestCase = {
  name: string;
  electionId: string;
  pkElection: string;
  committeePKs: string[];
  digest: string;
  signature: string;
  signer: string;
};

const fixture: { cases: DigestCase[] } = JSON.parse(
  readFileSync(join(__dirname, '../fixtures/geg-digests.json'), 'utf8')
);

const ONE = fixture.cases.find(c => c.name === 'three_keypers')!;

function hex(b: Buffer): string {
  return `0x${b.toString('hex')}`;
}

describe('GEG-DKG-RESULT-v1 digest', () => {
  it('has vectors covering more than one committee size', () => {
    // Guards the fixture itself: a single-case fixture would pass while proving
    // nothing about the offset table.
    expect(fixture.cases.length).toBeGreaterThanOrEqual(3);
    expect(
      new Set(fixture.cases.map(c => c.committeePKs.length)).size
    ).toBeGreaterThan(1);
  });

  it.each(fixture.cases.map(c => [c.name, c] as [string, DigestCase]))(
    'reproduces the Python digest for %s',
    (_name, c) => {
      expect(hex(dkgResultDigest(c))).toBe(c.digest.toLowerCase());
    }
  );

  it.each(fixture.cases.map(c => [c.name, c] as [string, DigestCase]))(
    'recovers the Python signer for %s',
    (_name, c) => {
      expect(recoverDigestSigner(dkgResultDigest(c), c.signature)).toBe(
        c.signer
      );
    }
  );

  // Each of these would change the digest, so each must change the signature that
  // verifies against it — otherwise a keyper could sign one result and have a
  // different one accepted.
  it('binds the election id', () => {
    const other = dkgResultDigest({
      ...ONE,
      electionId: `0x${'22'.repeat(32)}`
    });
    expect(hex(other)).not.toBe(ONE.digest);
    expect(recoverDigestSigner(other, ONE.signature)).not.toBe(ONE.signer);
  });

  it('binds the joint public key', () => {
    const other = dkgResultDigest({
      ...ONE,
      pkElection: `0x${'ab'.repeat(96)}`
    });
    expect(hex(other)).not.toBe(ONE.digest);
  });

  it('binds every committee key', () => {
    const swapped = [...ONE.committeePKs];
    swapped[0] = `0x${'ee'.repeat(96)}`;
    expect(hex(dkgResultDigest({ ...ONE, committeePKs: swapped }))).not.toBe(
      ONE.digest
    );
  });

  it('binds committee order, not just membership', () => {
    // Reordering keys reassigns which keyper owns which share, so it must not
    // produce the same digest.
    const reversed = [...ONE.committeePKs].reverse();
    expect(hex(dkgResultDigest({ ...ONE, committeePKs: reversed }))).not.toBe(
      ONE.digest
    );
  });

  it('binds committee size', () => {
    expect(
      hex(
        dkgResultDigest({ ...ONE, committeePKs: ONE.committeePKs.slice(0, 2) })
      )
    ).not.toBe(ONE.digest);
  });

  it.each([
    ['short election id', { electionId: `0x${'11'.repeat(31)}` }],
    ['long election id', { electionId: `0x${'11'.repeat(33)}` }],
    ['short pkElection', { pkElection: `0x${'aa'.repeat(95)}` }],
    ['non-hex election id', { electionId: `0x${'zz'.repeat(32)}` }],
    ['empty committee', { committeePKs: [] }],
    ['short committee key', { committeePKs: [`0x${'bb'.repeat(95)}`] }]
  ])('rejects %s rather than digesting it', (_label, override) => {
    expect(() => dkgResultDigest({ ...ONE, ...(override as any) })).toThrow(
      GegDigestError
    );
  });

  it('accepts field values without the 0x prefix', () => {
    expect(
      hex(
        dkgResultDigest({
          electionId: ONE.electionId.slice(2),
          pkElection: ONE.pkElection.slice(2),
          committeePKs: ONE.committeePKs.map(p => p.slice(2))
        })
      )
    ).toBe(ONE.digest);
  });

  // A malformed signature must be indistinguishable from a wrong one, so the
  // caller can answer with one uniform status.
  it.each([
    ['garbage', '0xdeadbeef'],
    ['empty', '0x'],
    ['not hex', 'nope']
  ])('returns null for a %s signature instead of throwing', (_label, sig) => {
    expect(recoverDigestSigner(dkgResultDigest(ONE), sig)).toBeNull();
  });

  it('recovers a different address for a signature over other content', () => {
    const otherDigest = dkgResultDigest({
      ...ONE,
      electionId: `0x${'33'.repeat(32)}`
    });
    expect(recoverDigestSigner(otherDigest, ONE.signature)).not.toBe(
      ONE.signer
    );
  });
});

// The freshness payload is written four times — geg's `request_nonce_payload`, the
// hub's and the browser's `requestNoncePayload`, and read back by two verifiers. If
// any of them disagrees by a byte, a stall signature stops verifying and a tally
// cannot be marked stalled at all. These vectors come from geg's Python, so this
// asserts agreement with the protocol rather than agreement with ourselves.
describe('requestNoncePayload — cross-language parity', () => {
  const vectors = JSON.parse(
    readFileSync(
      join(
        __dirname,
        '../../../../packages/geg-parity/vectors/request-nonce.json'
      ),
      'utf8'
    )
  ) as {
    cases: {
      name: string;
      op: string;
      electionId: string;
      payload: string;
      digest: string;
      signature: string;
      signer: string;
    }[];
  };

  it('has vectors to check', () => {
    expect(vectors.cases.length).toBeGreaterThan(0);
  });

  it.each(vectors.cases.map(c => [c.name, c] as const))(
    'reproduces %s',
    (_name, c) => {
      // The timestamp is recovered from the vector's own payload, so the encoding is
      // what is under test rather than a number we also chose.
      const issuedAt = Number(BigInt(c.payload));
      expect(`0x${requestNoncePayload(issuedAt).toString('hex')}`).toBe(
        c.payload
      );
      expect(
        `0x${requestDigest(c.op, c.electionId, requestNoncePayload(issuedAt)).toString('hex')}`
      ).toBe(c.digest);
      // And a signature geg produced over it recovers to geg's signer here.
      expect(
        recoverDigestSigner(
          Buffer.from(c.digest.slice(2), 'hex'),
          c.signature
        )?.toLowerCase()
      ).toBe(c.signer.toLowerCase());
    }
  );

  it('refuses a non-integer or negative timestamp rather than encoding nonsense', () => {
    expect(() => requestNoncePayload(-1)).toThrow();
    expect(() => requestNoncePayload(1.5)).toThrow();
  });
});
