name: Promote API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to promote
        type: choice
        options: [testnet, mainnet]
        required: true

jobs:
  promote:
    uses: ./.github/workflows/_promote-app.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      app_key: api
      app_name: sx-api
