name: CI

on: [push]

jobs:
  lint-build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test
      - run: yarn test:integration
